"""Copyright (c) 2026 Irene Elices. All Rights Reserved.
Use of this source code is govern by GPL-3.0 license that 
can be found in the LICENSE file"""

"""
pyloric_plot_r2_shift.py
==========================
Generates the R²(Period, LPPD delay) vs cycle-lag figures for two
pyloric simulations: one with modulation and one without, from the
pickles produced by pyloric_precompute.py.

Each simulation produces its own separate figure.

Usage
---
    python pyloric_plot_r2_shift.py --pkl-mod mod_data.pkl --pkl-nomod nomod_data.pkl
    python pyloric_plot_r2_shift.py --pkl-mod mod_data.pkl --pkl-nomod nomod_data.pkl \\
        --max-shift 15

Generated plots
---------------
    {base_mod}_lppd_period_r2_shift.svg     R²(Period, LPPD delay) vs lag — with modulation
    {base_nomod}_lppd_period_r2_shift.svg   R²(Period, LPPD delay) vs lag — without modulation
"""

import pickle
import argparse
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ─── global configuration ───────────────────────────────────────────────────
plt.rcParams.update({'font.size': 20})
plt.rcParams['svg.fonttype'] = 'none'


# ─── interval plots ──────────────────────────────────────────────────────────

def plot_lppd_period_r2_shift(intervals, max_shift=10, label="",
                               out="pyloric_lppd_period_r2_shift.png"):
    from scipy.stats import pearsonr

    lppd   = np.array(intervals["LP_ABPD_delay"]) * 1000.0
    period = np.array(intervals["Periodo"])        * 1000.0

    lags = np.arange(0, max_shift + 1)
    r2   = np.full(len(lags), np.nan)

    for k in lags:
        if k == 0:
            x, y = period, lppd
        else:
            x, y = period[:-k], lppd[k:]
        if len(x) > 2:
            r, _ = pearsonr(x, y)
            r2[k] = r ** 2

    fig, ax = plt.subplots(figsize=(7*1.4, 4*1.4))
    ax.set_xlabel('Cycle lag')
    ax.set_ylabel('R²')
    ax.set_ylim(0, 1)
    ax.set_xticks(lags)
    ax.yaxis.grid(True, color='#EEEEEE', lw=0.5)
    ax.xaxis.grid(True, color='#EEEEEE', lw=0.5)
    ax.set_axisbelow(True)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.plot(lags, r2, color="#d62728", lw=1.9, marker='o', markersize=8, zorder=3)
    ax.set_title(f'R²(Period[i], LPPD delay[i+k]) — shift 0..{max_shift} cycles\n{label}',
                 fontsize=10, fontweight='bold')
    plt.tight_layout()
    plt.savefig(out)
    plt.close(fig)


# ─── argparse ────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--pkl-mod", required=True,
                   help="Pickle generated by pyloric_data.py (with-modulation simulation)")
    p.add_argument("--pkl-nomod", required=True,
                   help="Pickle generated by pyloric_data.py (without-modulation simulation)")
    p.add_argument("--max-shift", type=int, default=10,
                   help="Maximum cycle lag to evaluate (default: 10)")
    p.add_argument("--out-mod",   default=None,
                   help="Path for the with-modulation figure (default: {base_mod}_lppd_period_r2_shift.svg)")
    p.add_argument("--out-nomod", default=None,
                   help="Path for the without-modulation figure (default: {base_nomod}_lppd_period_r2_shift.svg)")
    return p.parse_args()


# ─── main ────────────────────────────────────────────────────────────────────

def main():
    args = parse_args()

    print(f"\n  Loading pickle (with modulation): {args.pkl_mod}")
    with open(args.pkl_mod, "rb") as f:
        data_mod = pickle.load(f)
    intervals_mod = data_mod["intervals"]
    label_mod     = data_mod["label"]
    base_mod      = label_mod
    print(f"  Simulation: {label_mod}")

    print(f"\n  Loading pickle (without modulation): {args.pkl_nomod}")
    with open(args.pkl_nomod, "rb") as f:
        data_nomod = pickle.load(f)
    intervals_nomod = data_nomod["intervals"]
    label_nomod     = data_nomod["label"]
    base_nomod      = label_nomod
    print(f"  Simulation: {label_nomod}")

    print("\n  R² vs lag (LPPD × Period) — with modulation...")
    plot_lppd_period_r2_shift(intervals_mod, max_shift=args.max_shift, label=label_mod,
                               out=args.out_mod or f"{base_mod}_lppd_period_r2_shift.svg")

    print("  R² vs lag (LPPD × Period) — without modulation...")
    plot_lppd_period_r2_shift(intervals_nomod, max_shift=args.max_shift, label=label_nomod,
                               out=args.out_nomod or f"{base_nomod}_lppd_period_r2_shift.svg")

    print("\n  Done.")


if __name__ == "__main__":
    main()
